#!/bin/bash
#
# Deploy arcane_cli_app Server to Google Cloud Run
#
# Generated by Oracular. Idempotent: every gcloud step gracefully handles
# already-existing resources. Cleanup steps at the end keep Artifact
# Registry storage and Cloud Run revision counts bounded.
#
# Prerequisites:
# 1. Google Cloud CLI installed and configured (gcloud >= 444.0.0)
# 2. Docker installed
# 3. Artifact Registry + Cloud Run APIs enabled (run `oracular check tools`)
# 4. Active gcloud account has roles/artifactregistry.admin and
#    roles/run.admin
#

set -e  # Exit on error

PROJECT_ID="FIREBASE_PROJECT_ID"
REGION="us-central1"
REGISTRY_NAME="cloud-run-source-deploy"
SERVICE_NAME="arcane_cli_app-server"

# Cleanup tunables — these are mirrored from the values Oracular's
# SetupConfig defaults to. Override locally if you need different
# retention.
ARTIFACT_KEEP_RECENT="5"
ARTIFACT_DELETE_OLDER_DAYS="30"
CLOUD_RUN_KEEP_REVISIONS="3"

echo "==> Building arcane_cli_app Server for deployment..."

# Copy models directory for Docker build context
echo "==> Copying models directory..."
cp -r ../arcane_models arcane_models

# Get dependencies
flutter pub get
cd arcane_models && flutter pub get && rm -rf .dart_tool && cd ..

# Build Docker image
echo "==> Building Docker image..."
docker build --platform linux/amd64 \
  -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REGISTRY_NAME}/${SERVICE_NAME}:latest .

# Clean up temporary models directory
rm -rf arcane_models

# Push to Artifact Registry
echo "==> Pushing image to Artifact Registry..."
docker push --platform linux/amd64 \
  ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REGISTRY_NAME}/${SERVICE_NAME}:latest

# Deploy to Cloud Run
echo "==> Deploying to Cloud Run..."
gcloud beta run deploy ${SERVICE_NAME} \
  --region=${REGION} \
  --project=${PROJECT_ID} \
  --image=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REGISTRY_NAME}/${SERVICE_NAME}:latest \
  --min-instances=0 \
  --memory=1Gi \
  --cpu=1 \
  --concurrency=10 \
  --cpu-boost \
  --timeout=3600s

# ─── Cleanup: Artifact Registry image versions ──────────────────────────────
# Apply the cleanup-policy.json shipped alongside this script. Keeps the
# N most-recent versions and deletes anything older than D days.
if [ -f "$(dirname "$0")/cleanup-policy.json" ]; then
  echo "==> Applying Artifact Registry cleanup policy..."
  gcloud artifacts repositories set-cleanup-policies ${REGISTRY_NAME} \
      --location ${REGION} \
      --project ${PROJECT_ID} \
      --policy "$(dirname "$0")/cleanup-policy.json" || \
    echo "WARNING: cleanup policy not applied (gcloud >= 444.0.0 required)"
else
  echo "WARNING: cleanup-policy.json not found alongside script — skipping AR cleanup"
fi

# ─── Cleanup: Cloud Run revisions ───────────────────────────────────────────
# Keep the latest $CLOUD_RUN_KEEP_REVISIONS revisions and delete anything
# older that is not currently routing traffic.
echo "==> Pruning old Cloud Run revisions for ${SERVICE_NAME} (keep latest ${CLOUD_RUN_KEEP_REVISIONS})..."
ALL_REVS=$(gcloud run revisions list \
    --service=${SERVICE_NAME} \
    --region=${REGION} \
    --project=${PROJECT_ID} \
    --sort-by="~creationTimestamp" \
    --format="value(metadata.name)" 2>/dev/null || true)

if [ -n "$ALL_REVS" ]; then
  TRAFFIC_REVS=$(gcloud run services describe ${SERVICE_NAME} \
      --region=${REGION} \
      --project=${PROJECT_ID} \
      --format="value(status.traffic.revisionName)" 2>/dev/null || true)

  COUNT=0
  for REV in $ALL_REVS; do
    COUNT=$((COUNT+1))
    if [ "$COUNT" -le "$CLOUD_RUN_KEEP_REVISIONS" ]; then
      continue
    fi
    if echo "$TRAFFIC_REVS" | grep -q "$REV"; then
      echo "  Skipping $REV (serving traffic)"
      continue
    fi
    echo "  Deleting old revision: $REV"
    gcloud run revisions delete $REV \
        --region=${REGION} \
        --project=${PROJECT_ID} \
        --quiet || echo "  WARNING: could not delete $REV"
  done
else
  echo "WARNING: could not list Cloud Run revisions — skipping prune"
fi

echo ""
echo "Deployment complete!"
echo "Service URL: https://${SERVICE_NAME}-[PROJECT-HASH].${REGION}.run.app"
