import 'dart:io';

import 'package:fast_log/fast_log.dart';
import 'package:path/path.dart' as p;

import '../models/setup_config.dart';
import '../models/template_info.dart';
import '../utils/setup_guidance.dart';
import '../version.dart';

/// Generates a `docs/` folder inside a created Oracular project containing
/// quick-start, command, deployment and troubleshooting how-tos. The folder
/// always contains an `index.md` with a table of contents and a permutation-
/// aware set of pages tailored to the chosen template / Firebase / server
/// flags.
class DocsGenerator {
  /// Path to the docs folder that lives at the root of the user project.
  static String docsDir(SetupConfig config) {
    return p.join(config.outputDir, 'docs');
  }

  /// Write a complete `docs/` folder. Existing files are overwritten so the
  /// guide always reflects the current configuration.
  static Future<Directory> write(SetupConfig config) async {
    final Directory dir = Directory(docsDir(config));
    if (!dir.existsSync()) {
      await dir.create(recursive: true);
    }

    final List<_DocPage> pages = _buildPages(config);

    for (final _DocPage page in pages) {
      final File f = File(p.join(dir.path, page.filename));
      await f.writeAsString(page.content);
      verbose('Wrote ${page.filename}');
    }

    final File index = File(p.join(dir.path, 'README.md'));
    await index.writeAsString(_buildIndex(config, pages));

    return dir;
  }

  static List<_DocPage> _buildPages(SetupConfig config) {
    final List<_DocPage> pages = <_DocPage>[
      _DocPage(
        filename: '01-getting-started.md',
        title: 'Getting Started',
        content: _gettingStarted(config),
      ),
      _DocPage(
        filename: '02-commands.md',
        title: 'Command Reference',
        content: _commands(config),
      ),
      _DocPage(
        filename: '03-project-structure.md',
        title: 'Project Structure',
        content: _projectStructure(config),
      ),
      _DocPage(
        filename: '04-development.md',
        title: 'Development Workflow',
        content: _development(config),
      ),
    ];

    if (config.useFirebase) {
      pages.add(
        _DocPage(
          filename: '05-firebase.md',
          title: 'Firebase Setup',
          content: _firebase(config),
        ),
      );
      pages.add(
        _DocPage(
          filename: '06-deployment.md',
          title: 'Deployment',
          content: _deployment(config),
        ),
      );
    } else {
      pages.add(
        _DocPage(
          filename: '05-firebase.md',
          title: 'Firebase (Enable Later)',
          content: _firebaseLater(config),
        ),
      );
    }

    if (config.createServer) {
      pages.add(
        _DocPage(
          filename: '07-server.md',
          title: 'Server Deployment',
          content: _server(config),
        ),
      );
    }

    if (config.createModels) {
      pages.add(
        _DocPage(
          filename: '08-models.md',
          title: 'Shared Models',
          content: _models(config),
        ),
      );
    }

    pages.add(
      _DocPage(
        filename: '09-troubleshooting.md',
        title: 'Troubleshooting',
        content: _troubleshooting(config),
      ),
    );

    pages.add(
      _DocPage(
        filename: '10-resources.md',
        title: 'Further Reading',
        content: _resources(config),
      ),
    );

    return pages;
  }

  static String _buildIndex(SetupConfig config, List<_DocPage> pages) {
    final StringBuffer buf = StringBuffer();
    buf.writeln('# ${config.baseClassName} Docs');
    buf.writeln();
    buf.writeln(
      'Generated by [Oracular](https://pub.dev/packages/oracular) v$oracularVersion'
      ' on ${DateTime.now().toIso8601String().substring(0, 10)}.',
    );
    buf.writeln();
    buf.writeln('## Project at a Glance');
    buf.writeln();
    buf.writeln('| Setting | Value |');
    buf.writeln('| --- | --- |');
    config.toDisplayMap().forEach((String k, String v) {
      buf.writeln('| $k | $v |');
    });
    buf.writeln();
    buf.writeln('## Contents');
    buf.writeln();
    for (int i = 0; i < pages.length; i++) {
      final _DocPage page = pages[i];
      buf.writeln('${i + 1}. [${page.title}](./${page.filename})');
    }
    buf.writeln();
    buf.writeln('## Quick Reference');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('# Run the project');
    buf.writeln('cd ${SetupGuidance.mainProjectName(config)}');
    buf.writeln(SetupGuidance.runCommand(config));
    buf.writeln();
    buf.writeln('# Re-open this guide');
    buf.writeln('oracular guide');
    buf.writeln('oracular open guide');
    buf.writeln('```');
    return buf.toString();
  }

  // ---------------------------------------------------------------------------
  // Page builders
  // ---------------------------------------------------------------------------

  static String _gettingStarted(SetupConfig config) {
    final String mainPath = SetupGuidance.mainProjectName(config);
    final String runCmd = SetupGuidance.runCommand(config);
    final StringBuffer buf = StringBuffer();
    buf.writeln('# Getting Started');
    buf.writeln();
    buf.writeln(
      'This guide gets ${config.baseClassName} running on your machine.',
    );
    buf.writeln();
    buf.writeln('## 1. Verify your environment');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('oracular check tools');
    if (config.useFirebase) {
      buf.writeln('oracular check firebase');
    }
    buf.writeln('```');
    buf.writeln();
    buf.writeln('## 2. Install dependencies');
    buf.writeln();
    buf.writeln(
      'Oracular already ran `${_pubGetCommand(config)}` for every package, '
      'but if you ever need to redo it manually:',
    );
    buf.writeln();
    buf.writeln('```bash');
    if (config.template.isFlutterApp) {
      buf.writeln('cd $mainPath && flutter pub get');
    } else {
      buf.writeln('cd $mainPath && dart pub get');
    }
    if (config.createModels) {
      buf.writeln('cd ../${config.modelsPackageName} && dart pub get');
    }
    if (config.createServer) {
      buf.writeln('cd ../${config.serverPackageName} && dart pub get');
    }
    buf.writeln('```');
    buf.writeln();
    buf.writeln('## 3. Run the app');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('cd $mainPath');
    buf.writeln(runCmd);
    buf.writeln('```');
    buf.writeln();
    if (config.template.isFlutterApp) {
      buf.writeln(
        '`flutter run` opens an interactive console. Press `r` to hot-reload, '
        '`R` to hot-restart, and `q` to quit.',
      );
    } else if (config.template.isJasprApp) {
      buf.writeln(
        'Jaspr serves at <http://localhost:8080> by default with hot reload. '
        'Pass `--port 9000` to change ports or `--release` for an optimized build.',
      );
    } else {
      buf.writeln(
        'Pass `--help` (or any other flag) to see the available CLI commands.',
      );
    }
    buf.writeln();
    if (config.useFirebase) {
      buf.writeln('## 4. Wire up Firebase');
      buf.writeln();
      buf.writeln('```bash');
      buf.writeln('cd ${config.outputDir}');
      buf.writeln('oracular deploy firebase-setup');
      buf.writeln('```');
      buf.writeln();
      buf.writeln(
        'See [Firebase Setup](./05-firebase.md) for the full step-by-step.',
      );
      buf.writeln();
    }
    if (config.createServer) {
      buf.writeln('## 5. Run the server locally');
      buf.writeln();
      buf.writeln('```bash');
      buf.writeln('cd ${config.serverPackageName}');
      buf.writeln('dart run bin/main.dart');
      buf.writeln('```');
      buf.writeln();
      buf.writeln(
        'See [Server Deployment](./07-server.md) for production deploys.',
      );
      buf.writeln();
    }
    return buf.toString();
  }

  static String _commands(SetupConfig config) {
    final StringBuffer buf = StringBuffer();
    buf.writeln('# Command Reference');
    buf.writeln();
    buf.writeln(
      'A complete index of every Oracular command and pubspec script available '
      'in this project.',
    );
    buf.writeln();

    buf.writeln('## Oracular - Setup & Wizard');
    buf.writeln();
    buf.writeln('| Command | Description |');
    buf.writeln('| --- | --- |');
    buf.writeln('| `oracular` | Launch the interactive setup wizard. |');
    buf.writeln('| `oracular --version` | Print the installed Oracular version. |');
    buf.writeln('| `oracular --help` | Show top-level command help. |');
    buf.writeln('| `oracular check tools` | Verify Flutter/Dart/Firebase CLI installations. |');
    buf.writeln('| `oracular check firebase` | Validate Firebase CLI auth. |');
    buf.writeln('| `oracular guide` | (Re)write the project setup guide and docs/ folder. |');
    buf.writeln('| `oracular guide --print` | Print the guide to stdout. |');
    buf.writeln();

    buf.writeln('## Oracular - Open');
    buf.writeln();
    buf.writeln(
      'Open project folders or remote consoles in the OS file browser / web '
      'browser without leaving the terminal.',
    );
    buf.writeln();
    buf.writeln('| Target | Opens |');
    buf.writeln('| --- | --- |');
    buf.writeln('| `oracular open root` | Project root folder. |');
    buf.writeln('| `oracular open app` | Main application folder. |');
    buf.writeln('| `oracular open guide` | The local setup guide. |');
    buf.writeln('| `oracular open config` | Generated `config/` folder. |');
    if (config.createModels) {
      buf.writeln('| `oracular open models` | Shared models package folder. |');
    }
    if (config.createServer) {
      buf.writeln('| `oracular open server` | Server package folder. |');
      if (config.firebaseProjectId != null) {
        buf.writeln('| `oracular open service-account` | Firebase service-account web console. |');
        buf.writeln('| `oracular open cloud-run` | Google Cloud Run console. |');
      }
    }
    if (config.useFirebase) {
      buf.writeln('| `oracular open firebase` | Firebase project overview. |');
      buf.writeln('| `oracular open auth` | Firebase Authentication console. |');
      buf.writeln('| `oracular open firestore` | Firestore database console. |');
      buf.writeln('| `oracular open storage` | Firebase Storage console. |');
      if (SetupGuidance.supportsWebHosting(config)) {
        buf.writeln('| `oracular open hosting` | Firebase Hosting console. |');
      }
    }
    buf.writeln();

    if (config.useFirebase) {
      buf.writeln('## Oracular - Deploy');
      buf.writeln();
      buf.writeln('| Command | Effect |');
      buf.writeln('| --- | --- |');
      buf.writeln('| `oracular deploy firebase-setup` | One-shot bootstrap: FlutterFire/Jaspr config, hosting init, GCP APIs. |');
      buf.writeln('| `oracular deploy generate-configs` | Regenerate `firebase_options.dart` / Jaspr Firebase JS config. |');
      buf.writeln('| `oracular deploy firestore` | Deploy `firestore.rules` and indexes. |');
      buf.writeln('| `oracular deploy storage` | Deploy `storage.rules`. |');
      if (SetupGuidance.supportsWebHosting(config)) {
        buf.writeln('| `oracular deploy hosting` | Deploy production web hosting. |');
        buf.writeln(
          '| `oracular deploy hosting-beta` | Deploy beta channel '
          '(${projectBetaUrl(config)}). |',
        );
      }
      buf.writeln();
    }

    buf.writeln('## Pubspec scripts (run from `${SetupGuidance.mainProjectName(config)}/`)');
    buf.writeln();
    buf.writeln(
      'Use `oracular scripts list` and `oracular scripts exec <name>` to discover '
      'and run scripts. Fuzzy matching is on - `br` resolves to `build_runner`, '
      '`runner` resolves to it too if unique.',
    );
    buf.writeln();

    if (config.template.isFlutterApp) {
      buf.writeln('### Flutter app scripts');
      buf.writeln();
      buf.writeln('| Script | Command |');
      buf.writeln('| --- | --- |');
      buf.writeln('| `dev` | `flutter run` |');
      buf.writeln('| `build_apk` | `flutter build apk --release` |');
      buf.writeln('| `build_ios` | `flutter build ios --release` |');
      buf.writeln('| `build_web` | `flutter build web --release` |');
      buf.writeln('| `test` | `flutter test` |');
      buf.writeln('| `analyze` | `flutter analyze` |');
      buf.writeln('| `clean` | `flutter clean` |');
      buf.writeln('| `build_runner` | `dart run build_runner build --delete-conflicting-outputs` |');
      buf.writeln();
    } else if (config.template.isJasprApp) {
      buf.writeln('### Jaspr scripts');
      buf.writeln();
      buf.writeln('| Script | Command |');
      buf.writeln('| --- | --- |');
      buf.writeln('| `serve` | `jaspr serve` |');
      buf.writeln('| `serve_release` | `jaspr serve --release` |');
      buf.writeln('| `build` | `jaspr build` |');
      buf.writeln('| `clean` | `jaspr clean` |');
      buf.writeln('| `killall` | `pkill -f "jaspr serve"` |');
      buf.writeln('| `build_runner` | `dart run build_runner build --delete-conflicting-outputs` |');
      buf.writeln('| `watch` | `dart run build_runner watch --delete-conflicting-outputs` |');
      buf.writeln('| `firebase_deploy` | Build then `firebase deploy --only hosting`. |');
      buf.writeln();
    } else if (config.template.isDartCli) {
      buf.writeln('### CLI app scripts');
      buf.writeln();
      buf.writeln('| Script | Command |');
      buf.writeln('| --- | --- |');
      buf.writeln('| `dev` | `dart run bin/main.dart --help` |');
      buf.writeln('| `compile` | Compile to a native executable. |');
      buf.writeln('| `test` | `dart test` |');
      buf.writeln('| `analyze` | `dart analyze` |');
      buf.writeln('| `format` | `dart format .` |');
      buf.writeln();
    }

    if (config.createServer) {
      buf.writeln('### Server scripts (run from `${config.serverPackageName}/`)');
      buf.writeln();
      buf.writeln('| Script | Command |');
      buf.writeln('| --- | --- |');
      buf.writeln('| `dev` | `dart run bin/main.dart` |');
      buf.writeln('| `deploy` | `./script_deploy.sh` |');
      buf.writeln('| `test` | `dart test` |');
      buf.writeln('| `analyze` | `dart analyze` |');
      buf.writeln();
    }

    return buf.toString();
  }

  static String _projectStructure(SetupConfig config) {
    final StringBuffer buf = StringBuffer();
    buf.writeln('# Project Structure');
    buf.writeln();
    buf.writeln('```text');
    buf.writeln('${p.basename(config.outputDir)}/');
    buf.writeln('|-- ${SetupGuidance.mainProjectName(config)}/'
        '              # ${SetupGuidance.mainProjectLabel(config)}');
    if (config.createModels) {
      buf.writeln('|-- ${config.modelsPackageName}/'
          '              # Shared models package');
    }
    if (config.createServer) {
      buf.writeln('|-- ${config.serverPackageName}/'
          '              # Dart REST API server');
    }
    buf.writeln('|-- config/                              # Setup metadata + Firebase JSON');
    buf.writeln('|-- references/                          # Vendored Arcane reference docs');
    buf.writeln('|-- docs/                                # This documentation folder');
    buf.writeln('|-- GET_STARTED.md                       # Auto-generated quick-start guide');
    buf.writeln('|-- README.md');
    buf.writeln('`-- ...');
    buf.writeln('```');
    buf.writeln();

    if (config.template.isFlutterApp) {
      buf.writeln('## Inside `${config.appName}/`');
      buf.writeln();
      buf.writeln('```text');
      buf.writeln('lib/');
      buf.writeln('|-- main.dart                        # App entrypoint');
      if (config.template == TemplateType.arcaneBeamer) {
        buf.writeln('|-- routes/                          # Beamer location definitions');
        buf.writeln('|-- screens/                         # Top-level screens');
      }
      if (config.template == TemplateType.arcaneDock) {
        buf.writeln('|-- tray/                            # Tray icon + menu');
        buf.writeln('|-- windows/                         # Mini-window components');
      }
      buf.writeln('|-- components/                      # Reusable widgets');
      buf.writeln('|-- services/                        # Domain logic & data access');
      buf.writeln('|-- utils/                           # Helpers, constants');
      if (config.useFirebase) {
        buf.writeln('`-- firebase_options.dart            # FlutterFire-generated config');
      }
      buf.writeln('```');
      buf.writeln();
    } else if (config.template.isJasprApp) {
      buf.writeln('## Inside `${config.webPackageName}/`');
      buf.writeln();
      buf.writeln('```text');
      buf.writeln('lib/');
      buf.writeln('|-- main.client.dart                # Client-side entrypoint');
      buf.writeln('|-- app.dart                        # Top-level <App/> component');
      buf.writeln('|-- routes/');
      buf.writeln('|   `-- app_router.dart             # Route table');
      buf.writeln('|-- screens/                        # Page-level components');
      buf.writeln('|-- components/                     # Reusable UI components');
      buf.writeln('`-- utils/');
      buf.writeln('    `-- constants.dart              # Route/app constants');
      buf.writeln('web/');
      buf.writeln('|-- index.html                      # HTML shell + Firebase JS hooks');
      buf.writeln('|-- styles.css                      # Global theme + reset');
      buf.writeln('`-- assets/');
      buf.writeln('```');
      buf.writeln();
    } else if (config.template.isDartCli) {
      buf.writeln('## Inside `${config.appName}/`');
      buf.writeln();
      buf.writeln('```text');
      buf.writeln('bin/');
      buf.writeln('`-- main.dart                       # CLI entrypoint');
      buf.writeln('lib/');
      buf.writeln('|-- cli/');
      buf.writeln('|   |-- commands.dart               # Command tree definition');
      buf.writeln('|   `-- handlers/                   # Implementation per command');
      buf.writeln('`-- services/                       # Reusable domain logic');
      buf.writeln('```');
      buf.writeln();
    }

    if (config.createServer) {
      buf.writeln('## Inside `${config.serverPackageName}/`');
      buf.writeln();
      buf.writeln('```text');
      buf.writeln('bin/');
      buf.writeln('|-- main.dart                       # Cloud Run / shelf entrypoint');
      buf.writeln('lib/');
      buf.writeln('|-- routes/                         # HTTP route handlers');
      buf.writeln('|-- middleware/                     # Auth, CORS, logging');
      buf.writeln('`-- services/                       # Domain layer');
      buf.writeln('Dockerfile                          # Container build');
      buf.writeln('script_deploy.sh                    # gcloud run deploy helper');
      buf.writeln('```');
      buf.writeln();
    }

    if (config.createModels) {
      buf.writeln('## Inside `${config.modelsPackageName}/`');
      buf.writeln();
      buf.writeln(
        'Pure-Dart package shared between the app and (optionally) the '
        'server. Add `@artifact` types here so JSON serialization stays '
        'consistent across tiers.',
      );
      buf.writeln();
    }
    return buf.toString();
  }

  static String _development(SetupConfig config) {
    final StringBuffer buf = StringBuffer();
    buf.writeln('# Development Workflow');
    buf.writeln();
    buf.writeln('## Hot reload / hot restart');
    buf.writeln();
    if (config.template.isFlutterApp) {
      buf.writeln(
        'While `flutter run` is attached, press `r` for hot reload, `R` for '
        'hot restart, `o` to switch the target platform, `q` to quit. Run '
        '`flutter run -d chrome` to launch the web build.',
      );
    } else if (config.template.isJasprApp) {
      buf.writeln(
        '`jaspr serve` watches the entire project for changes and rebuilds '
        'on save. To restart manually: `oracular scripts exec killall && '
        'oracular scripts exec serve`.',
      );
    } else {
      buf.writeln(
        'CLI apps re-run on each invocation; for tight loops use '
        '`dart run --enable-vm-service bin/main.dart` and connect a debugger.',
      );
    }
    buf.writeln();

    buf.writeln('## Code generation');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('cd ${SetupGuidance.mainProjectName(config)}');
    buf.writeln('dart run build_runner build --delete-conflicting-outputs');
    buf.writeln('# or, while editing models continuously:');
    buf.writeln('dart run build_runner watch --delete-conflicting-outputs');
    buf.writeln('```');
    buf.writeln();

    if (config.createModels) {
      buf.writeln('Run the same commands inside `${config.modelsPackageName}/` '
          'when you change `@artifact` annotated classes.');
      buf.writeln();
    }

    buf.writeln('## Adding a screen / route');
    buf.writeln();
    if (config.template == TemplateType.arcaneTemplate) {
      buf.writeln(
        '1. Create a new widget under `lib/components/` (or `lib/screens/`).\n'
        '2. Push it from a button: `Navigator.of(context).push(MaterialPageRoute(...))`.\n'
        '3. Or - swap to the Beamer template later for declarative routing.',
      );
    } else if (config.template == TemplateType.arcaneBeamer) {
      buf.writeln(
        '1. Define a new `BeamLocation` in `lib/routes/`.\n'
        '2. Add it to the router list in `lib/main.dart`.\n'
        '3. Navigate with `context.beamToNamed(\'/your-route\')`.',
      );
    } else if (config.template.isJasprApp) {
      buf.writeln(
        '1. Add a route constant in `lib/utils/constants.dart`.\n'
        '2. Create the screen widget under `lib/screens/`.\n'
        '3. Wire the route case in `lib/routes/app_router.dart`.\n'
        '4. Link to it via `Button.primary(href: AppRoutes.your, label: ...)`.',
      );
    }
    buf.writeln();

    buf.writeln('## Linting & formatting');
    buf.writeln();
    buf.writeln('```bash');
    if (config.template.isFlutterApp) {
      buf.writeln('flutter analyze');
      buf.writeln('dart format .');
    } else {
      buf.writeln('dart analyze');
      buf.writeln('dart format .');
    }
    buf.writeln('```');
    buf.writeln();

    buf.writeln('## Testing');
    buf.writeln();
    buf.writeln('```bash');
    if (config.template.isFlutterApp) {
      buf.writeln('flutter test');
    } else {
      buf.writeln('dart test');
    }
    buf.writeln('```');
    return buf.toString();
  }

  static String _firebase(SetupConfig config) {
    final String projectId = config.firebaseProjectId ?? 'YOUR_PROJECT_ID';
    final StringBuffer buf = StringBuffer();
    buf.writeln('# Firebase Setup');
    buf.writeln();
    buf.writeln('## Project: `$projectId`');
    buf.writeln();
    buf.writeln('Useful consoles:');
    buf.writeln();
    buf.writeln(
      '- Overview: ${SetupGuidance.firebaseOverviewUrl(projectId)}\n'
      '- Authentication: ${SetupGuidance.firebaseAuthenticationConsoleUrl(projectId)}\n'
      '- Firestore: ${SetupGuidance.firebaseFirestoreConsoleUrl(projectId)}\n'
      '- Storage: ${SetupGuidance.firebaseStorageConsoleUrl(projectId)}\n'
      '- Hosting: ${SetupGuidance.firebaseHostingConsoleUrl(projectId)}',
    );
    buf.writeln();

    buf.writeln('## Bootstrap (run once)');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('cd ${config.outputDir}');
    buf.writeln('oracular deploy firebase-setup');
    buf.writeln('```');
    buf.writeln();
    buf.writeln(
      'This:\n'
      '- creates / reuses a Firebase web app\n'
      '- generates `firebase_options.dart` (Flutter) or `firebase_config.js` (Jaspr)\n'
      '- enables required Google Cloud APIs\n'
      '- writes `firebase.json`, `.firebaserc`, `firestore.rules`, `storage.rules`',
    );
    buf.writeln();

    buf.writeln('## Manual checklist');
    buf.writeln();
    buf.writeln(
      '1. **Authentication:** Open the auth console and enable the providers '
      'you need (Google / Email-Password / Anonymous).\n'
      '2. **Firestore:** Create the database (Native mode) the first time you '
      'visit the console. Pick a region close to your users.\n'
      '3. **Storage:** Click "Get started" if your app uploads files.\n'
      '4. **Indexes / rules:** Edit `firestore.rules`, `firestore.indexes.json`, '
      '`storage.rules` then `oracular deploy firestore` / `oracular deploy storage`.',
    );
    buf.writeln();

    buf.writeln('## Regenerate config');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('oracular deploy generate-configs');
    buf.writeln('```');
    return buf.toString();
  }

  static String _firebaseLater(SetupConfig config) {
    final String configPath = p.join(
      config.outputDir,
      'config',
      'setup_config.env',
    );
    final StringBuffer buf = StringBuffer();
    buf.writeln('# Enabling Firebase Later');
    buf.writeln();
    buf.writeln(
      'You created this project without Firebase. To turn it on:',
    );
    buf.writeln();
    buf.writeln('1. Edit `$configPath` and set:');
    buf.writeln();
    buf.writeln('   ```env');
    buf.writeln('   USE_FIREBASE=yes');
    buf.writeln('   FIREBASE_PROJECT_ID=<your-project-id>');
    buf.writeln('   ```');
    buf.writeln();
    buf.writeln('2. From the project root run:');
    buf.writeln();
    buf.writeln('   ```bash');
    buf.writeln('   oracular deploy firebase-setup');
    buf.writeln('   ```');
    buf.writeln();
    buf.writeln('3. Re-generate this docs/ folder:');
    buf.writeln();
    buf.writeln('   ```bash');
    buf.writeln('   oracular guide');
    buf.writeln('   ```');
    return buf.toString();
  }

  static String _deployment(SetupConfig config) {
    final String projectId = config.firebaseProjectId ?? 'YOUR_PROJECT_ID';
    final StringBuffer buf = StringBuffer();
    buf.writeln('# Deployment');
    buf.writeln();
    if (SetupGuidance.supportsWebHosting(config)) {
      buf.writeln('## Firebase Hosting');
      buf.writeln();
      buf.writeln('```bash');
      buf.writeln('# Production');
      buf.writeln('oracular deploy hosting');
      buf.writeln('# Beta channel');
      buf.writeln('oracular deploy hosting-beta');
      buf.writeln('```');
      buf.writeln();
      buf.writeln('Live URLs after deploy:');
      buf.writeln();
      buf.writeln(
        '- Production: <${SetupGuidance.releaseHostingUrl(projectId)}>\n'
        '- Beta: <${SetupGuidance.betaHostingUrl(projectId)}>',
      );
      buf.writeln();
      buf.writeln(
        'First-time beta deploys need the channel created once:',
      );
      buf.writeln();
      buf.writeln('```bash');
      buf.writeln('firebase hosting:sites:create $projectId-beta --project $projectId');
      buf.writeln('```');
      buf.writeln();
    }

    buf.writeln('## Firestore rules / indexes');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('oracular deploy firestore');
    buf.writeln('```');
    buf.writeln();
    buf.writeln('## Storage rules');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('oracular deploy storage');
    buf.writeln('```');
    buf.writeln();
    if (config.createServer) {
      buf.writeln('## Server (Cloud Run)');
      buf.writeln();
      buf.writeln('See [Server Deployment](./07-server.md).');
    }
    return buf.toString();
  }

  static String _server(SetupConfig config) {
    final StringBuffer buf = StringBuffer();
    final String projectId = config.firebaseProjectId ?? 'YOUR_PROJECT_ID';
    final String serverPath = config.serverPackageName;

    buf.writeln('# Server Deployment');
    buf.writeln();
    buf.writeln('Server package: `$serverPath`');
    buf.writeln();

    buf.writeln('## Local development');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('cd $serverPath');
    buf.writeln('dart run bin/main.dart');
    buf.writeln('```');
    buf.writeln();
    buf.writeln('The server reads `PORT` from the environment (defaults to 8080).');
    buf.writeln();

    buf.writeln('## Service account key');
    buf.writeln();
    buf.writeln(
      '1. Open the Firebase service-accounts console:\n'
      '   <${SetupGuidance.firebaseServiceAccountUrl(projectId)}>\n'
      '2. Click **Generate new private key**.\n'
      '3. Save the JSON file as `$serverPath/service-account.json`.\n'
      '4. Keep at most two backups (`.bak.1`, `.bak.2`) when rotating keys.',
    );
    buf.writeln();
    buf.writeln(
      'Tip: `oracular` can do this interactively - it opens the destination '
      'folder in Finder/Explorer and auto-detects the dropped file.',
    );
    buf.writeln();

    buf.writeln('## Deploy to Cloud Run');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('cd $serverPath');
    buf.writeln('./script_deploy.sh');
    buf.writeln('```');
    buf.writeln();
    buf.writeln('Cloud Run console: <${SetupGuidance.cloudRunConsoleUrl(projectId)}>');
    return buf.toString();
  }

  static String _models(SetupConfig config) {
    final StringBuffer buf = StringBuffer();
    buf.writeln('# Shared Models');
    buf.writeln();
    buf.writeln(
      'Pure-Dart package `${config.modelsPackageName}` is the canonical home '
      'for any data type that crosses tier boundaries. Generate JSON '
      'serialization with `package:artifact`:',
    );
    buf.writeln();
    buf.writeln('```dart');
    buf.writeln("import 'package:artifact/artifact.dart';");
    buf.writeln();
    buf.writeln('part \'user.g.dart\';');
    buf.writeln();
    buf.writeln('@artifact');
    buf.writeln('class User extends ArtifactObject<User> {');
    buf.writeln('  String? id;');
    buf.writeln('  String? email;');
    buf.writeln('  DateTime? createdAt;');
    buf.writeln('}');
    buf.writeln('```');
    buf.writeln();
    buf.writeln('Then regenerate:');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('cd ${config.modelsPackageName}');
    buf.writeln('dart run build_runner build --delete-conflicting-outputs');
    buf.writeln('```');
    buf.writeln();
    buf.writeln(
      'Both `${SetupGuidance.mainProjectName(config)}` and the server (when '
      'enabled) depend on this package via path:',
    );
    buf.writeln();
    buf.writeln('```yaml');
    buf.writeln('dependencies:');
    buf.writeln('  ${config.modelsPackageName}:');
    buf.writeln('    path: ../${config.modelsPackageName}');
    buf.writeln('```');
    return buf.toString();
  }

  static String _troubleshooting(SetupConfig config) {
    final StringBuffer buf = StringBuffer();
    buf.writeln('# Troubleshooting');
    buf.writeln();

    buf.writeln('## `pub get` complains about jaspr / arcane_auth_jaspr');
    buf.writeln();
    buf.writeln(
      'The base Jaspr template uses `jaspr ^0.23.0`. There is no published '
      '`arcane_auth_jaspr` that supports `0.23.x` yet, so do not add it. If '
      'an old project pulls it in, remove the dependency line and re-run '
      '`dart pub get`.',
    );
    buf.writeln();

    buf.writeln('## `pub get` complains about Flutter SDK in Jaspr');
    buf.writeln();
    buf.writeln(
      'Oracular vendors a pure-Dart `jpatch` shim into `.oracular_deps/` and '
      'adds a `dependency_overrides` block to your `pubspec.yaml` whenever a '
      'Jaspr / pure-Dart package depends on `arcane_models`. If you delete '
      'that folder, re-run the wizard or copy `.oracular_deps/jpatch` from a '
      'fresh project.',
    );
    buf.writeln();

    buf.writeln('## FlutterFire / Firebase config keeps failing');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('oracular check firebase');
    buf.writeln('firebase login --reauth');
    buf.writeln('oracular deploy firebase-setup');
    buf.writeln('```');
    buf.writeln();
    buf.writeln(
      'Pre-flight checks: you must be the project Owner, Firebase tools must '
      'be `>= 13.x`, and the Firebase project must already exist (Oracular '
      'will not create the project itself).',
    );
    buf.writeln();

    buf.writeln('## Hot reload not picking up changes');
    buf.writeln();
    if (config.template.isFlutterApp) {
      buf.writeln(
        'Hot reload skips changes to `main()`, top-level state, and code-gen '
        'output. Press `R` for a hot **restart** instead. If you edited '
        '`@artifact` types, run `build_runner build` first.',
      );
    } else if (config.template.isJasprApp) {
      buf.writeln(
        '`jaspr serve` watches the project but builders are slower. Run '
        '`oracular scripts exec build_runner` once after large edits, then '
        '`oracular scripts exec serve`.',
      );
    } else {
      buf.writeln(
        'CLI apps do not hot reload - re-run the entrypoint after each edit.',
      );
    }
    buf.writeln();

    if (config.createServer) {
      buf.writeln('## Cloud Run: 401 / 403');
      buf.writeln();
      buf.writeln(
        'Verify `service-account.json` is the Firebase Admin key (not a generic '
        'GCP service account) and that it has the **Firebase Admin SDK** role. '
        'Re-deploy with `./script_deploy.sh` after replacing the key.',
      );
      buf.writeln();
    }

    buf.writeln('## Rebuilding the docs/ folder');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('oracular guide');
    buf.writeln('```');
    return buf.toString();
  }

  static String _resources(SetupConfig config) {
    final StringBuffer buf = StringBuffer();
    buf.writeln('# Further Reading');
    buf.writeln();
    buf.writeln('## Oracular');
    buf.writeln();
    buf.writeln('- pub.dev: <https://pub.dev/packages/oracular>');
    buf.writeln('- Repo: <https://github.com/ArcaneArts/Oracular>');
    buf.writeln();
    buf.writeln('## Arcane');
    buf.writeln();
    if (config.template.isFlutterApp) {
      buf.writeln('- arcane: <https://pub.dev/packages/arcane>');
      buf.writeln('- arcane_user: <https://pub.dev/packages/arcane_user>');
    }
    if (config.template.isJasprApp) {
      buf.writeln('- arcane_jaspr: <https://pub.dev/packages/arcane_jaspr>');
      buf.writeln('- arcane_jaspr_shadcn (in monorepo): '
          '<https://github.com/ArcaneArts/arcane_jaspr/tree/master/packages/arcane_jaspr_shadcn>');
    }
    buf.writeln('- artifact: <https://pub.dev/packages/artifact>');
    buf.writeln('- fast_log: <https://pub.dev/packages/fast_log>');
    buf.writeln();

    buf.writeln('## Frameworks');
    buf.writeln();
    if (config.template.isFlutterApp) {
      buf.writeln('- Flutter: <https://docs.flutter.dev>');
      buf.writeln('- Flutter web deploy: <https://docs.flutter.dev/deployment/web>');
    }
    if (config.template.isJasprApp) {
      buf.writeln('- Jaspr docs: <https://docs.jaspr.site>');
    }
    if (config.template.isDartCli) {
      buf.writeln('- darted_cli: <https://pub.dev/packages/darted_cli>');
    }
    buf.writeln('- Dart language tour: <https://dart.dev/guides/language>');
    buf.writeln();

    buf.writeln('## Firebase / GCP');
    buf.writeln();
    buf.writeln('- Firebase docs: <https://firebase.google.com/docs>');
    buf.writeln('- FlutterFire setup: <https://firebase.google.com/docs/flutter/setup>');
    if (config.createServer) {
      buf.writeln('- Cloud Run: <https://cloud.google.com/run/docs>');
    }
    return buf.toString();
  }

  static String _pubGetCommand(SetupConfig config) {
    return config.template.isFlutterApp ? 'flutter pub get' : 'dart pub get';
  }

  static String projectBetaUrl(SetupConfig config) {
    final String pid = config.firebaseProjectId ?? 'YOUR_PROJECT_ID';
    return SetupGuidance.betaHostingUrl(pid);
  }
}

class _DocPage {
  final String filename;
  final String title;
  final String content;
  const _DocPage({
    required this.filename,
    required this.title,
    required this.content,
  });
}
